- name: variables
  hosts: local
  connection: local
  vars:  # play level variables
    COURSE: "AWS DEVOPS"
    DURATION: 2MONTHS
    TRAINER: shivakumar
  tasks: 
  - name: print the variables
    vars: #task level variables
      COURSE: ansible
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"

  - name: print the variables1
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"
 

        