- name: variables
  hosts: local
  connection: local
  vars:  # Play level variable
    GREET: "PLAY"
  vars_files:
  - course.yaml
  vars_prompt: 
  - name: GREET
    prompt: Enter the value
    private: false
  tasks:
  - name: print the variables
    vars: 
      GREET: "TASK"
    ansible.builtin.debug:
        msg: "Hello from {{ GREET }}"




#1. command line or args
#2. task level
#3. Files
#4. Prompt
#5. play
#6. inventory
#7. roles


