- name: variables
  hosts: local
  connection: local
  vars:  # play level variable
    GREET: "PLAY"
  Vars_files:
  - course.yaml
  vars_prompt: 
  - name: GREET
    prompt: Enter the value
    private: false
  tasks:
  - name: print the variables
    vars: 
      GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"